language: node_js
node_js:
  - "node"
script:
  - npm run build
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: "juke-13562"
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: "juke-staging"
    on:
      branch: staging
