export const UPDATE_BREADCRUMBS = 'UPDATE_BREADCRUMBS'
export const UPDATE_SIDENAV = 'UPDATE_SIDENAV'

// Left Nav
export const UPDATE_LEFT_NAV = 'UPDATE_LEFT_NAV'

// Right Nav
export const TOGGLE_RIGHT_NAV = 'TOGGLE_RIGHT_NAV'
